# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Alternately flip the signs of elements of a vector
#' 
#' @param v A numerical vector
#' @export
alternate_signs <- function(v) {
    .Call(`_withrcpp_alternate_signs`, v)
}

