# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cholesky decomposition
#' 
#' @param X A positive definite matrix
#' @export
my_chol <- function(X) {
    .Call(`_witharmadillo_my_chol`, X)
}

