---
title: "Packages in the Wild"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Packages in the Wild}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

We plan for this section to expand over time.  Please let us know^[Email [Jacob](http://faculty.marshall.usc.edu/jacob-bien/) or post an issue [here](https://github.com/jacobbien/litr-project/issues)] if you'd like your litr-knitted package to appear here.

```{r, eval=TRUE, include=FALSE}
library(dplyr)
library(stringr)
```

```{r, eval=TRUE, echo=FALSE, results='asis'}
path <- "https://github.com/{user}/{repo}/blob/{branch}/"
shorten <- function(pkgname, max_char = 13, extra = 5) {
  n <- nchar(pkgname)
  too_long <- which(n > max_char)
  if (length(too_long) == 0) return(pkgname)
  pkgname[too_long] <- paste0(
    stringr::str_sub(pkgname[too_long], end = max_char - 2 - extra),
    "..")
  return(pkgname)
}

tibble(
  user = c("jacobbien",
           "jacobbien",
           "jacobbien",
           "ArkajyotiSaha",
           "gregfaletto"),
  repo = c("jsm2023-project",
           "jsm2022-project",
           "rleastsquares-project",
           "independencepvalue-project",
           "cssr-project"),
  branch = c("main",
             "main",
             "main",
             "main",
             "main"),
  pkg_name = c("jsm2023",
               "jsm2022",
               "rleastsquares",
               "independencepvalue",
               "cssr"),
  description = c(rep("Navigate the JSM program from the comfort of an R console", 2),
                  "Perform least squares (a package coded in a live demo)",
                  "Test independence between groups of Gaussian variables",
                  "Cluster stability selection"),
  website = c("https://jacobbien.github.io/jsm2023-project/",
              "",
              "",
              "https://arkajyotisaha.github.io/independencepvalue-project/",
              "https://gregfaletto.github.io/cssr-project/"),
  generated_html_website = c("[create-jsm2023.html](https://jacobbien.github.io/jsm2023-project/create-jsm2023.html)",
                             "",
                             "",
                             "",
                             "[bookdown](https://gregfaletto.github.io/cssr-project/create/)"),
    
  ) %>% 
  transmute(
    `Package name` = if_else(
      nchar(website) == 0,
      pkg_name,
      as.character(str_glue('<a href="{website}">{pkg_name}</a>'))),
    Description = description,
    `Rmd source file` = as.character(str_glue(paste0(
        "[create-{shorten(pkg_name)}.Rmd](",
        path,
        "create-{pkg_name}.Rmd)"
    ))),
    `Generated html` = if_else(
      generated_html_website == "",
      as.character(str_glue(paste0(
      "[create-{shorten(pkg_name)}.html](https://htmlpreview.github.io/?",
      path,
      "create-{pkg_name}.html)"
      ))),
      generated_html_website),
    `Generated R package` = str_glue(paste0(
      "[{pkg_name}/](", path, "{pkg_name})"
    ))
  ) %>% 
  mutate(`Rmd source file` = if_else(str_detect(`Rmd source file`, "create-cssr.Rmd"),
                                    "[index.Rmd](https://github.com/gregfaletto/cssr-project/blob/main/index.Rmd)",
                                    `Rmd source file`)) %>%
knitr::kable()
```

